### ISSUE TITLE
[Feature request] Console HUD

### ISSUE THREAD

**Issue by Ales724** [LazyDuchess/OffTheRecordPatch#1]
Could you please make the HUD looking the same way as on console? On PC there's really apparent compression on the hud but it looks relatively clean on the console versions. Here are images comparing the HUD from PC & X360 version

![SS](https://github.com/user-attachments/assets/8d7bb679-ad4b-4281-bda4-ffb4e7e028fd)
![SA](https://github.com/user-attachments/assets/99b4d016-82b5-40ad-bca2-855ce992866e)

![videoframe_7514](https://github.com/user-attachments/assets/22443075-da20-4965-add2-6ac0a6d0a6b5)
![videoframe_751424](https://github.com/user-attachments/assets/b847be80-993e-4ebe-a8aa-bf2d0f1cf4b0)

**Comment by TemporaryPSP** [comment]
This is not something OffTheRecordPatch tackles. It's a texture edit. You'd have to get the assets from Xbox 360 and convert to PC. There are tools available.

**Comment by LazyDuchess** [comment]
That's correct, unless it's some problem in the game's rendering code I won't tackle it within this patch. 

If the problem is baked into the game's code somehow and isn't a texture issue let me know and I can reopen this and look into it at a later date.
